// Ngân hàng mở rộng cho bài tập kỹ năng. Viết gọn: đáp án ĐÚNG luôn ở vị trí đầu,
// hàm `q` chuyển thành SkillExercise (answer = 0). Thứ tự hiển thị được xáo khi làm bài
// (withShuffledOptions), nên học viên không thấy quy luật vị trí.

import type { Criterion, ExerciseKind, SkillExercise } from './skill-exercises';

const CRIT: Record<ExerciseKind, Criterion> = {
  grammar: 'gra', linking: 'cc', collocation: 'lr', paraphrase: 'ta', overview: 'ta',
};

let counter: Partial<Record<ExerciseKind, number>> = {};

function q(
  kind: ExerciseKind, question: string, correct: string, wrong: [string, string, string],
  explanation: string, context?: string,
): SkillExercise {
  const n = (counter[kind] = (counter[kind] ?? 0) + 1);
  const id = `x-${kind.slice(0, 3)}-${String(n).padStart(2, '0')}`;
  return { id, kind, criterion: CRIT[kind], context, question, options: [correct, ...wrong], answer: 0, explanation };
}

export const EXTRA_EXERCISES: SkillExercise[] = [
  // ── Grammar ──
  q('grammar', 'Choose the correct sentence.',
    'Despite the rise in prices, demand remained stable.',
    ['Despite of the rise in prices, demand remained stable.', 'Despite the prices rose, demand remained stable.', 'In spite the rise in prices, demand remained stable.'],
    '"Despite" is followed directly by a noun phrase or -ing form: never "of", and never a full clause.'),
  q('grammar', 'Choose the correct sentence.',
    'The graph shows how much energy is consumed.',
    ['The graph shows how much is energy consumed.', 'The graph shows how much energy does consumed.', 'The graph shows that how much energy is consumed.'],
    'Indirect questions keep statement word order (subject before verb): "how much energy is consumed".'),
  q('grammar', 'Sales ___ sharply between 2010 and 2015.',
    'rose',
    ['have risen', 'rise', 'are rising'],
    'A finished past period (between 2010 and 2015) needs the past simple: rose.'),
  q('grammar', 'Choose the correct sentence.',
    'Fewer people own cars than ten years ago.',
    ['Less people own cars than ten years ago.', 'Fewer people owns cars than ten years ago.', 'Fewer of people own cars than ten years ago.'],
    'Use "fewer" with countable nouns (people) and a plural verb (own).'),
  q('grammar', 'Choose the correct sentence.',
    'Not only did the population grow, but the economy also expanded.',
    ['Not only the population grew, but the economy also expanded.', 'Not only did the population grew, but the economy also expanded.', 'Not only the population did grow, but the economy also expanded.'],
    'After a negative adverbial such as "Not only", the auxiliary comes before the subject (did the population grow).'),
  q('grammar', 'Choose the correct sentence.',
    'If more people had cycled to work, pollution would have fallen.',
    ['If more people have cycled to work, pollution would have fallen.', 'If more people had cycled to work, pollution would fall in the past.', 'If more people would have cycled to work, pollution would have fallen.'],
    'Third conditional: If + past perfect, would have + past participle. Never use "would have" in the if-clause.'),
  q('grammar', 'Choose the sentence with correct article use.',
    'The government should invest in education.',
    ['Government should invest in the education.', 'The government should invest in an education.', 'A government should invest in the education.'],
    '"The government" refers to a specific, known body; "education" in general is uncountable and takes no article.'),
  q('grammar', 'Choose the correct sentence.',
    'Students who work part-time often find it hard to concentrate.',
    ['Students who works part-time often find it hard to concentrate.', 'Students who work part-time often finds it hard to concentrate.', 'Students which work part-time often find it hard to concentrate.'],
    'The relative clause verb agrees with the plural "students" (work), and "who" (not "which") refers to people.'),
  q('grammar', 'Choose the correct sentence.',
    'Having finished the survey, the researchers analysed the data.',
    ['Having finished the survey, the data was analysed by the researchers.', 'Finishing the survey, the data were analysed by the researchers.', 'After finished the survey, the researchers analysed the data.'],
    'A participle clause must share its subject with the main clause: the researchers finished and analysed. In the first two options, "the data" would wrongly be the one that finished the survey.'),
  q('grammar', 'Choose the correct sentence.',
    'The majority of respondents were in favour of the plan.',
    ['The majority of respondents was in favour of the plan.', 'The majority of respondents were in favour for the plan.', 'Majority of respondents were in favour of the plan.'],
    'With "the majority of + plural noun" the verb is plural, and the phrase is "in favour of". "The majority" needs its article.'),
  q('grammar', 'Choose the correct sentence.',
    'Each of the candidates was interviewed twice.',
    ['Each of the candidates were interviewed twice.', 'Each of candidates was interviewed twice.', 'Each of the candidate was interviewed twice.'],
    '"Each" is singular, so it takes a singular verb (was), and "of the" is followed by a plural noun (candidates).'),
  q('grammar', 'The proportion of elderly people ___ over the past decade.',
    'has grown steadily',
    ['grew steadily', 'have grown steadily', 'is growing steadily since'],
    '"Over the past decade" links the past to now, so the present perfect is used, and "proportion" is singular: has grown.'),

  // ── Linking ──
  q('linking', 'Choose the best connector: "Public transport is cheap. ___, it reduces traffic congestion."',
    'Moreover',
    ['However', 'Otherwise', 'Instead'],
    'The second sentence adds a further advantage, so an addition connector (Moreover) fits. However, Otherwise and Instead signal contrast or alternatives.'),
  q('linking', 'Choose the best connector: "Some people prefer cities; ___, others enjoy rural life."',
    'on the other hand',
    ['as a result', 'for instance', 'in addition'],
    'The two halves contrast two groups, so "on the other hand" is the logical link.'),
  q('linking', 'Choose the best connector: "The company cut its prices. ___, sales rose by 20%."',
    'As a result',
    ['Nevertheless', 'In contrast', 'Similarly'],
    'The sales rise is the consequence of the price cut, so a result connector is needed.'),
  q('linking', 'Choose the best connector: "___ the heavy rain, the match went ahead."',
    'Despite',
    ['Because of', 'Due to', 'Therefore'],
    'The match went ahead against the odds, so a concession (Despite) is needed. "Because of" and "Due to" give causes; "Therefore" is not followed by a noun phrase like this.'),
  q('linking', 'Which sentence uses "whereas" correctly?',
    'Urban areas are densely populated, whereas rural areas are sparsely populated.',
    ['Urban areas are densely populated, whereas of rural areas.', 'Whereas urban areas are densely populated.', 'Urban areas are densely populated whereas, because rural areas are empty.'],
    '"Whereas" joins two complete clauses to contrast them. The other options leave a fragment or add a second conjunction.'),
  q('linking', 'Which sentence has the clearest reference?',
    'Many students use social media. This habit can reduce their study time.',
    ['Many students use social media. It can reduce their study time.', 'Many students use social media. That can reduce their study time too.', 'Many students use social media. They can reduce their study time.'],
    '"This habit" names exactly what is being referred to. "It", "That" and "They" could refer to students, social media or the whole idea.'),
  q('linking', 'Choose the best connector: "Exercise improves health. ___, it boosts mental well-being."',
    'Furthermore',
    ['Consequently', 'By contrast', 'Rather'],
    'Both sentences give benefits, so the second adds to the first: Furthermore.'),
  q('linking', 'Choose the best connector: "___ the government raises taxes, public services will suffer."',
    'Unless',
    ['Whereas', 'Although', 'Since then'],
    '"Unless" (= if not) states the condition under which the result holds. The other options do not express a condition.'),
  q('linking', 'Choose the best phrase to begin a concluding paragraph.',
    'In conclusion',
    ['For example', 'On the contrary', 'First of all'],
    '"In conclusion" signals the end of the essay; the others belong in the body.'),
  q('linking', 'Choose the best connector: "Fossil fuels are cheap; ___, they cause serious pollution."',
    'nevertheless',
    ['therefore', 'similarly', 'for example'],
    'The two ideas conflict (cheap versus polluting), so a concession connector such as "nevertheless" fits.'),
  q('linking', 'Which is the best way to give an example?',
    'Many cities have introduced congestion charges; London, for instance, charges drivers to enter the centre.',
    ['Many cities have introduced congestion charges, London charges drivers to enter the centre.', 'Many cities have introduced congestion charges, so London charges drivers to enter the centre.', 'Many cities have introduced congestion charges; London, moreover, charges drivers.'],
    'A semicolon with "for instance" cleanly introduces an example. The first option is a comma splice, and "so" or "moreover" give the wrong logic.'),
  q('linking', 'Choose the best connector: "Online courses are flexible. ___, they can feel isolating."',
    'That said',
    ['In addition', 'Consequently', 'Likewise'],
    'The sentence introduces a drawback after an advantage, so a contrast phrase (That said) is needed.'),

  // ── Collocation ──
  q('collocation', 'Choose the natural collocation: "The government should ___ a ban on plastic bags."',
    'introduce',
    ['do', 'perform', 'produce'],
    'You "introduce" (or impose) a ban. The other verbs do not collocate with "ban".'),
  q('collocation', 'Choose the natural collocation: "Air pollution poses a serious ___ to public health."',
    'threat',
    ['damage', 'harm', 'trouble'],
    '"Pose a threat" is a fixed collocation; "damage", "harm" and "trouble" do not collocate with "pose".'),
  q('collocation', 'Choose the natural collocation: "Employers should ___ equal opportunities to all applicants."',
    'provide',
    ['make', 'do', 'bring'],
    'You "provide" or "offer" opportunities; "make" and "do" do not collocate with it.'),
  q('collocation', 'Choose the natural collocation: "There has been a ___ increase in online shopping."',
    'sharp',
    ['powerful', 'heavy', 'tall'],
    '"A sharp increase" is the standard phrase for a rapid rise. "Powerful", "heavy" and "tall" do not collocate with "increase".'),
  q('collocation', 'Choose the natural collocation: "Governments must ___ action to tackle climate change."',
    'take',
    ['make', 'do', 'give'],
    '"Take action" is the fixed collocation.'),
  q('collocation', 'Choose the natural collocation: "Many students find it hard to ___ a balance between study and work."',
    'strike',
    ['hold', 'put', 'catch'],
    '"Strike a balance" (or "achieve a balance") is the natural phrase.'),
  q('collocation', 'Choose the natural collocation: "The new policy has had a significant ___ on small businesses."',
    'impact',
    ['result', 'cause', 'reason'],
    '"Have an impact on" is a common academic collocation. "Result", "cause" and "reason" do not fit this structure.'),
  q('collocation', 'Choose the natural collocation: "Rising costs have ___ many families into debt."',
    'pushed',
    ['lifted', 'shot', 'carried'],
    '"Push someone into debt" is the natural phrase in this sense.'),
  q('collocation', 'Choose the natural collocation: "It is widely ___ that exercise improves concentration."',
    'accepted',
    ['agreed on', 'thought about', 'said with'],
    '"It is widely accepted that…" is a standard academic opener. The other options are not idiomatic here.'),
  q('collocation', 'Choose the natural collocation: "Young people are more ___ to the influence of advertising."',
    'susceptible',
    ['attached', 'fond', 'suitable'],
    '"Susceptible to" means easily influenced. The other adjectives change the meaning or take other prepositions.'),
  q('collocation', 'Choose the natural collocation: "The city has ___ a rapid expansion in the last decade."',
    'undergone',
    ['done', 'made', 'played'],
    'You "undergo" a change or an expansion. "Done", "made" and "played" do not fit.'),
  q('collocation', 'Choose the natural collocation: "Tourism makes a major ___ to the local economy."',
    'contribution',
    ['help', 'donation', 'addition of'],
    '"Make a contribution to" is fixed. "Help" is not used this way, and "donation" means giving money.'),

  // ── Paraphrase ──
  q('paraphrase', 'Which is the best paraphrase of: "The number of cars has increased dramatically."?',
    'There has been a sharp rise in the number of vehicles on the road.',
    ['The number of cars has increased dramatically.', 'Cars are very numerous now.', 'Many cars have been bought by people.'],
    'A good paraphrase changes vocabulary and structure (increase → rise, cars → vehicles) while keeping the meaning. The others copy the original or lose meaning.'),
  q('paraphrase', 'Which is the best paraphrase of: "Some people think children should start school at an early age."?',
    'It is believed by certain individuals that youngsters ought to begin formal education early.',
    ['Some people think children should start school at an early age.', 'Children should never start school early.', 'Schools are important for young children.'],
    'The correct answer changes the words and the sentence structure without changing the claim. The others repeat it or change the meaning.'),
  q('paraphrase', 'Which is the best paraphrase of "a growing number of people"?',
    'an increasing number of individuals',
    ['a big number of humans', 'a growing number of people', 'lots of the people now'],
    '"An increasing number of individuals" changes the adjective and the noun while keeping the meaning (a number, not a proportion).'),
  q('paraphrase', 'Which is the best paraphrase of: "The chart shows the percentage of households with internet access."?',
    'The chart illustrates the proportion of homes that were connected to the internet.',
    ['The chart shows the percentage of households with internet access.', 'The chart is about the internet.', 'The graph illustrates how many computers were sold.'],
    'Shows → illustrates, percentage → proportion, households → homes, keeping the same meaning. The last option changes the topic.'),
  q('paraphrase', 'Which is the best paraphrase of: "Governments should spend more money on public transport."?',
    'Public transport ought to receive greater funding from governments.',
    ['Governments should spend more money on public transport.', 'Governments should stop funding public transport.', 'Public transport is expensive for governments.'],
    'The paraphrase turns the sentence into a passive-style structure with new vocabulary, keeping the same recommendation.'),
  q('paraphrase', 'Which is the best paraphrase of "young people"?',
    'the younger generation',
    ['juveniles', 'the youthfuls', 'people of young'],
    '"The younger generation" is a natural synonym phrase. The other options are unnatural or change the register.'),
  q('paraphrase', 'Which is the best paraphrase of: "Many people now work from home."?',
    'Remote working has become common among employees.',
    ['Many people now work from home.', 'Employees like their offices.', 'Home is a good place for people.'],
    'Changes "work from home" to "remote working" and restructures the sentence, keeping the meaning.'),
  q('paraphrase', 'Which is the best paraphrase of: "Air pollution is a major problem in big cities."?',
    'Poor air quality is a serious issue in large urban areas.',
    ['Air pollution is a major problem in big cities.', 'Big cities are polluted and dirty.', 'Air is a problem in cities.'],
    'Synonyms are used for each key idea (pollution → poor air quality, major → serious, big cities → large urban areas).'),
  q('paraphrase', 'Which is the best paraphrase of "a large proportion of"?',
    'a significant share of',
    ['a large proportion of', 'a big amount from', 'the large part with'],
    '"A significant share of" changes the words and keeps the meaning and grammar.'),
  q('paraphrase', 'Which is the best paraphrase of: "Technology has made communication easier."?',
    'Advances in technology have simplified the way people communicate.',
    ['Technology has made communication easier.', 'Communication is a kind of technology.', 'People do not communicate now.'],
    'A good paraphrase uses new vocabulary (advances, simplified) and structure while keeping the claim.'),
  q('paraphrase', 'Which is the best paraphrase of: "The price of oil fell sharply in 2015."?',
    'Oil prices dropped dramatically in 2015.',
    ['The price of oil fell sharply in 2015.', 'Oil became a little cheaper in 2015.', 'In 2015 the oil price rose sharply.'],
    'The paraphrase keeps the meaning (a big fall) with new words. "A little cheaper" changes the size; "rose" changes the direction.'),
  q('paraphrase', 'Which is the best paraphrase of: "It is essential to protect the environment."?',
    'Safeguarding the natural world is of vital importance.',
    ['It is essential to protect the environment.', 'The environment is essential.', 'We protect nature sometimes.'],
    'Different wording (safeguarding, the natural world, vital importance) with the same meaning.'),

  // ── Overview ──
  q('overview', 'Which is the best overview of a Task 1 line graph in which sales of tea fell steadily while coffee sales rose steadily from 2000 to 2020?',
    'Overall, coffee sales climbed steadily over the period, whereas tea sales moved in the opposite direction.',
    ['In 2000, tea sales were 50 units and coffee sales were 30 units.', 'The graph shows coffee and tea sales.', 'I think coffee is more popular than tea.'],
    'An overview gives the main trends without detailed numbers, opinions or a vague description.'),
  q('overview', 'Which is the best overview of a table in which Japan had the highest and Brazil the lowest recycling rate in every year?',
    'Overall, Japan had the highest recycling rate throughout, while Brazil had the lowest.',
    ['Japan recycled 80% in 2010 and Brazil 20% in 2010.', 'The table gives recycling rates.', 'Recycling is important for all countries.'],
    'The overview states the main features across all years, not single figures or general statements.'),
  q('overview', 'A Task 1 process diagram shows how paper is made in five stages. Which is the best overview?',
    'Overall, the process consists of five stages, beginning with the collection of wood and ending with the packaging of finished paper.',
    ['First, wood is cut into small pieces and then heated.', 'The diagram shows a process.', 'Making paper is bad for forests.'],
    'A process overview gives the number of stages and the start and end, not the detail of one stage or an opinion.'),
  q('overview', 'Task 2: "Some people think zoos should be closed. To what extent do you agree?" Which introduction has the clearest position?',
    'While some argue that zoos are cruel, I believe they should stay open because they protect endangered species and educate the public.',
    ['Zoos are places where there are animals and people come to see them.', 'This essay will discuss zoos and their advantages and disadvantages.', 'Zoos are a very controversial topic in the world today.'],
    'A strong introduction paraphrases the topic and states a clear position with reasons. The others give no position.'),
  q('overview', 'Task 2: "Many people work long hours. What are the causes and what can be done?" Which thesis is best?',
    'Long working hours are mainly caused by economic pressure and workplace culture, and both employers and governments can reduce them through better regulation.',
    ['Many people work long hours.', 'I will write about working hours in this essay.', 'Work is very important in life and people must work hard.'],
    'The best thesis answers both parts of the question (causes and solutions) in one clear statement.'),
  q('overview', 'A Task 1 map shows a village before and after a new shopping centre. Which is the best overview?',
    'Overall, the village became far more developed, with farmland replaced by a shopping centre and a larger road network.',
    ['There was a field in the north and a road in the east.', 'The maps show a village.', 'The shopping centre is a good change.'],
    'The overview summarises the main changes, not individual locations or opinions.'),
  q('overview', 'Which sentence is NOT suitable in a Task 1 overview?',
    'In my opinion, the government should build more roads.',
    ['Overall, car ownership rose in every region.', 'The most striking feature is the rapid growth in Asia.', 'In general, Europe remained the lowest throughout.'],
    'Task 1 describes data; personal opinions and recommendations do not belong in it.'),
  q('overview', 'A pie chart compares the ways a family spends its income. Which is the best overview?',
    'Overall, housing accounted for the largest share of spending, while entertainment took up the smallest.',
    ['Housing was 35%, food was 20% and transport was 15%.', 'The pie chart is about money.', 'Families should spend less on housing.'],
    'A good overview states the largest and smallest categories without a list of figures.'),
  q('overview', 'Task 2: "Is the increase in international tourism a positive or negative development?" Which is the best thesis?',
    'Although mass tourism damages local environments, I believe its economic benefits outweigh the drawbacks.',
    ['Tourism is when people travel to other countries.', 'There are advantages and disadvantages of tourism.', 'This essay will talk about tourism and travel.'],
    'A thesis takes a position on the question (here, benefits outweigh drawbacks), not just names the topic.'),
  q('overview', 'A bar chart shows that unemployment fell in most of the six countries between 2010 and 2020, but rose in one. Which is the best overview?',
    'Overall, unemployment declined in five of the six countries over the decade, with the single exception of Spain.',
    ['Unemployment in Spain was 20% in 2010.', 'The chart shows six countries.', 'Unemployment is a difficult problem for governments.'],
    'It states the general trend and the one exception, without detailed data or opinions.', 'The exceptional country is Spain.'),
  q('overview', 'Task 2: "Some people prefer to live in a city, others in the countryside. Discuss both views and give your opinion." Which introduction is best?',
    'While city life offers career opportunities and entertainment, others value the peace of the countryside; in my view, the countryside is the better place to raise a family.',
    ['Cities and the countryside are different places to live in.', 'In this essay I will discuss cities and the countryside.', 'Living is important for everyone in the world.'],
    'It paraphrases both views and gives a clear opinion, as the question requires.'),
  q('overview', 'Which is the best way to begin the overview of a Task 1 graph?',
    'Overall, …',
    ['In my personal opinion, …', 'The first thing I see is …', 'To be honest, …'],
    '"Overall" (or "In general") is the conventional signal for the overview, which describes the main trends objectively.'),
];
